// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: UniTexture.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Editor {

  /// <summary>Holder for reflection information generated from UniTexture.proto</summary>
  public static partial class UniTextureReflection {

    #region Descriptor
    /// <summary>File descriptor for UniTexture.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static UniTextureReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBVbmlUZXh0dXJlLnByb3RvEgZFZGl0b3IiZAoKVW5pVGV4dHVyZRIQCghl",
            "eHBfbmFtZRgBIAEoCRIOCgZwcm9tcHQYAiABKAkSDAoEc2VlZBgDIAEoBRIU",
            "Cgxpbml0X3RleHR1cmUYBCABKAwSEAoIb2JqX2ZpbGUYBSABKAxiBnByb3Rv",
            "Mw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Editor.UniTexture), global::Editor.UniTexture.Parser, new[]{ "ExpName", "Prompt", "Seed", "InitTexture", "ObjFile" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class UniTexture : pb::IMessage<UniTexture>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UniTexture> _parser = new pb::MessageParser<UniTexture>(() => new UniTexture());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<UniTexture> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Editor.UniTextureReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UniTexture() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UniTexture(UniTexture other) : this() {
      expName_ = other.expName_;
      prompt_ = other.prompt_;
      seed_ = other.seed_;
      initTexture_ = other.initTexture_;
      objFile_ = other.objFile_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UniTexture Clone() {
      return new UniTexture(this);
    }

    /// <summary>Field number for the "exp_name" field.</summary>
    public const int ExpNameFieldNumber = 1;
    private string expName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ExpName {
      get { return expName_; }
      set {
        expName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "prompt" field.</summary>
    public const int PromptFieldNumber = 2;
    private string prompt_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Prompt {
      get { return prompt_; }
      set {
        prompt_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "seed" field.</summary>
    public const int SeedFieldNumber = 3;
    private int seed_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Seed {
      get { return seed_; }
      set {
        seed_ = value;
      }
    }

    /// <summary>Field number for the "init_texture" field.</summary>
    public const int InitTextureFieldNumber = 4;
    private pb::ByteString initTexture_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString InitTexture {
      get { return initTexture_; }
      set {
        initTexture_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "obj_file" field.</summary>
    public const int ObjFileFieldNumber = 5;
    private pb::ByteString objFile_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString ObjFile {
      get { return objFile_; }
      set {
        objFile_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as UniTexture);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(UniTexture other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ExpName != other.ExpName) return false;
      if (Prompt != other.Prompt) return false;
      if (Seed != other.Seed) return false;
      if (InitTexture != other.InitTexture) return false;
      if (ObjFile != other.ObjFile) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ExpName.Length != 0) hash ^= ExpName.GetHashCode();
      if (Prompt.Length != 0) hash ^= Prompt.GetHashCode();
      if (Seed != 0) hash ^= Seed.GetHashCode();
      if (InitTexture.Length != 0) hash ^= InitTexture.GetHashCode();
      if (ObjFile.Length != 0) hash ^= ObjFile.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ExpName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ExpName);
      }
      if (Prompt.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Prompt);
      }
      if (Seed != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Seed);
      }
      if (InitTexture.Length != 0) {
        output.WriteRawTag(34);
        output.WriteBytes(InitTexture);
      }
      if (ObjFile.Length != 0) {
        output.WriteRawTag(42);
        output.WriteBytes(ObjFile);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ExpName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ExpName);
      }
      if (Prompt.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Prompt);
      }
      if (Seed != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Seed);
      }
      if (InitTexture.Length != 0) {
        output.WriteRawTag(34);
        output.WriteBytes(InitTexture);
      }
      if (ObjFile.Length != 0) {
        output.WriteRawTag(42);
        output.WriteBytes(ObjFile);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ExpName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ExpName);
      }
      if (Prompt.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Prompt);
      }
      if (Seed != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Seed);
      }
      if (InitTexture.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(InitTexture);
      }
      if (ObjFile.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(ObjFile);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(UniTexture other) {
      if (other == null) {
        return;
      }
      if (other.ExpName.Length != 0) {
        ExpName = other.ExpName;
      }
      if (other.Prompt.Length != 0) {
        Prompt = other.Prompt;
      }
      if (other.Seed != 0) {
        Seed = other.Seed;
      }
      if (other.InitTexture.Length != 0) {
        InitTexture = other.InitTexture;
      }
      if (other.ObjFile.Length != 0) {
        ObjFile = other.ObjFile;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ExpName = input.ReadString();
            break;
          }
          case 18: {
            Prompt = input.ReadString();
            break;
          }
          case 24: {
            Seed = input.ReadInt32();
            break;
          }
          case 34: {
            InitTexture = input.ReadBytes();
            break;
          }
          case 42: {
            ObjFile = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ExpName = input.ReadString();
            break;
          }
          case 18: {
            Prompt = input.ReadString();
            break;
          }
          case 24: {
            Seed = input.ReadInt32();
            break;
          }
          case 34: {
            InitTexture = input.ReadBytes();
            break;
          }
          case 42: {
            ObjFile = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
